server:
  port: 8081 # 重新开一个端口

spring:
  application:
    name: dubbo-consumer
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        ephemeral: false
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

# 配置dubbo
dubbo:
  registry:
    address: spring-cloud://localhost # 使用spring cloud的注册中心
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1 # 端口从20880开始，自动增加
  consumer:
    check: false
